/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AutoFoldPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  foldLevel: "fold-all",
  delay: 500
};
var AutoFoldPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "auto-fold-current-file",
      name: "Fold current file",
      callback: () => {
        this.foldCurrentFile();
      }
    });
    this.addCommand({
      id: "auto-fold-all",
      name: "Fold all",
      callback: () => {
        this.foldCurrentFile("fold-all");
      }
    });
    for (let i = 1; i <= 6; i++) {
      this.addCommand({
        id: `auto-fold-level-${i}`,
        name: `Fold level ${i}`,
        callback: () => {
          this.foldCurrentFile(String(i));
        }
      });
    }
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (file) {
          setTimeout(() => {
            this.foldCurrentFile();
          }, this.settings.delay);
        }
      })
    );
    this.addSettingTab(new AutoFoldSettingTab(this.app, this));
  }
  foldCurrentFile(targetLevel) {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (view) {
      try {
        const levelToUse = targetLevel || this.settings.foldLevel;
        let commandId = "editor:fold-all";
        if (levelToUse !== "fold-all") {
          commandId = `editor:fold-level-${levelToUse}`;
        }
        this.app.commands.executeCommandById(commandId);
      } catch (error) {
        console.error("Auto Fold: Error executing fold command", error);
      }
    }
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var AutoFoldSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Auto Fold Settings" });
    new import_obsidian.Setting(containerEl).setName("Fold Level").setDesc("Select which level of headings to fold when opening a file.").addDropdown((dropdown) => dropdown.addOption("fold-all", "Fold All").addOption("1", "Level 1 (H1)").addOption("2", "Level 2 (H2)").addOption("3", "Level 3 (H3)").addOption("4", "Level 4 (H4)").addOption("5", "Level 5 (H5)").addOption("6", "Level 6 (H6)").setValue(this.plugin.settings.foldLevel).onChange(async (value) => {
      this.plugin.settings.foldLevel = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Delay (ms)").setDesc("Delay before folding (in milliseconds). Increase this if folding is inconsistent.").addSlider((slider) => slider.setLimits(0, 2e3, 50).setValue(this.plugin.settings.delay).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.delay = value;
      await this.plugin.saveSettings();
    }));
  }
};
